import type { Metadata } from "next";
import "./globals.css";
import Providers from "../../components/universal/Providers";
import { Source_Code_Pro } from "next/font/google";
import Frame from "../../components/universal/Frame";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
const SourceCodePro = Source_Code_Pro({
	subsets: ["latin"],
	preload: true,
	display: "swap"
});

export const metadata: Metadata = {
	title: "CatInPajams | A Rookie Engineer",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Providers>
			<html lang="en">
				<body className={SourceCodePro.className}>
					<Frame>
						<AppRouterCacheProvider options={{ enableCssLayer: true }}>
							{children}
						</AppRouterCacheProvider>
					</Frame>
				</body>
			</html>
		</Providers>
	);
}
